// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace ChatWidget.API.Infrastructure.EntityFramework
{
    public partial class AgentInbox
    {
        public int Id { get; set; }
        public int AgentId { get; set; }
        public Guid InboxId { get; set; }
        public string AgentInboxId { get; set; }

        public virtual Inbox Inbox { get; set; }
    }
}