// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace ChatWidget.API.Infrastructure.EntityFramework
{
    public partial class Inbox
    {
        public Inbox()
        {
            AgentInboxes = new HashSet<AgentInbox>();
            ChannelInboxes = new HashSet<ChannelInbox>();
            Users = new HashSet<User>();
        }

        public Guid Id { get; set; }
        public DateTime CreateDate { get; set; }

        public virtual ICollection<AgentInbox> AgentInboxes { get; set; }
        public virtual ICollection<ChannelInbox> ChannelInboxes { get; set; }
        public virtual ICollection<User> Users { get; set; }
    }
}