// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace ChatWidget.API.Infrastructure.EntityFramework
{
    public partial class User
    {
        public User()
        {
            ChannelUsers = new HashSet<ChannelUser>();
            Messages = new HashSet<Message>();
        }

        public Guid Id { get; set; }
        public Guid InboxId { get; set; }
        public int ChannelId { get; set; }
        public DateTime CreateDate { get; set; }

        public virtual Inbox Inbox { get; set; }
        public virtual ICollection<ChannelUser> ChannelUsers { get; set; }
        public virtual ICollection<Message> Messages { get; set; }
    }
}