// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace TalkBox.Infrastructure.EntityFramework
{
    public partial class Message
    {
        public Guid Id { get; set; }
        public Guid UserId { get; set; }
        public int Owner { get; set; }
        public string Type { get; set; }
        public string Message1 { get; set; }
        public DateTime SentDate { get; set; }

        public virtual User User { get; set; }
    }
}